name: Sync to Hugging Face Hub

on:
  push:
    branches: [master] 
    paths:
      - 'apps/backend/**' # Trigger only on backend folder changes
      - '.github/workflows/sync_to_huggingface.yml' # Also trigger on changes to this workflow file
  pull_request:
    branches: [master]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/sync_to_huggingface.yml' # Also trigger on

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://harshitajoshi067:$HF_TOKEN@huggingface.co/spaces/harshitajoshi067/Neuro-Hire main
