name: Sync to Hugging Face Hub

on:
  push:
    branches: [master] 
    paths:
      - 'apps/backend/**'
      - '.github/workflows/sync_to_huggingface.yml' 
  pull_request:
    branches: [master]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/sync_to_huggingface.yml' 

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugging Face Hub CLI
        run: pip install huggingface_hub

      - name: Upload to Spaces via CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # This uploads the entire folder structure directly into your Space repo
          hf upload harshitajoshi067/Neuro-Hire . . --repo-type space --token=$HF_TOKEN
